VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cBox"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Left As Long
Public Top As Long
Public Right As Long
Public Bottom As Long

Public Window As String

Public Function Width() As Long
    Width = Right - Left
End Function

Public Function Height() As Long
    Height = Bottom - Top
End Function
